fullnameOverride: pronunt-ingestion-service

namespace:
  create: false
  name: prism

image:
  repository: ghcr.io/pronunt/pronunt-ingestion-service
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 8000

service:
  enabled: true
  type: ClusterIP
  port: 8000
  targetPort: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: pronunt-ingestion-service.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

env:
  config:
    APP_NAME: pronunt-ingestion-service
    APP_ENV: production
    APP_HOST: 0.0.0.0
    APP_PORT: "8000"
    LOG_LEVEL: INFO
    GITHUB_API_URL: https://api.github.com
    AUTH_SERVICE_URL: http://pronunt-auth-service:8000
    RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
  secret:
    GITHUB_TOKEN: change-me

